/**
 * Mock Article Data
 * Sample articles for development when RSS feeds are not available
 */

import type { Article } from '@/types/rss';

const generateDate = (daysAgo: number, hour: number, minute: number): Date => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hour, minute, 0, 0);
  return date;
};

const mockArticles: Article[] = [
  // ─── Nieuws ──────────────────────────────────────────────────────────────────
  {
    id: '1',
    title: 'Nvidia RTX 5090 verschijnt in Nederland: vanaf €2.199 bij Coolblue en Alternate',
    summary: 'De Nvidia GeForce RTX 5090 met 32 GB GDDR7-geheugen is nu verkrijgbaar in Nederland. De kaart levert tot 70% meer prestaties dan de RTX 4090.',
    content: '',
    url: 'https://tweakers.net/nieuws/231456/nvidia-rtx-5090-nederland',
    imageUrl: 'https://placehold.co/800x400/76B900/white?text=RTX+5090',
    publishedAt: generateDate(0, 10, 30),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '2',
    title: 'Samsung Galaxy S25 Ultra nu verkrijgbaar: prijzen vanaf €1.299',
    summary: 'Samsung brengt de Galaxy S25 Ultra uit met Snapdragon 8 Elite-chip, 200 MP camera en titanium frame. Beschikbaar bij alle grote Nederlandse webshops.',
    content: '',
    url: 'https://tweakers.net/nieuws/231455/samsung-galaxy-s25-ultra-verkrijgbaar',
    imageUrl: 'https://placehold.co/800x400/1A73E8/white?text=Galaxy+S25+Ultra',
    publishedAt: generateDate(0, 9, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '3',
    title: 'Apple brengt iOS 18.4 uit met verbeterde Siri en nieuwe emoji',
    summary: 'Apple rolt iOS 18.4 uit voor alle ondersteunde iPhones. De update bevat een slimmere Siri, nieuwe emoji en verbeteringen voor Apple Intelligence.',
    content: '',
    url: 'https://tweakers.net/nieuws/231454/apple-ios-18-4',
    imageUrl: 'https://placehold.co/800x400/555555/white?text=iOS+18.4',
    publishedAt: generateDate(0, 7, 15),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '4',
    title: 'AMD Ryzen 9 9950X3D officieel aangekondigd: tot 20% sneller in games',
    summary: 'AMD onthult de Ryzen 9 9950X3D met 16 cores en 144 MB 3D V-Cache. De processor verschijnt in maart voor een adviesprijs van €649. // Bron: https://www.amd.com/en/products/processors/desktops/ryzen/9000-series/amd-ryzen-9-9950x3d.html',
    content: '',
    url: 'https://tweakers.net/nieuws/231453/amd-ryzen-9-9950x3d',
    imageUrl: 'https://placehold.co/800x400/ED1C24/white?text=Ryzen+9950X3D',
    publishedAt: generateDate(0, 6, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '5',
    title: 'Nintendo Switch 2 aangekondigd: 7,9-inch LCD, grotendeels backwards compatible',
    summary: 'Nintendo onthult de Switch 2 met een groter 7,9-inch scherm, magnetische Joy-Con-controllers en backwards compatibility met de meeste Switch-games. // Bron: https://en.wikipedia.org/wiki/Nintendo_Switch_2',
    content: '',
    url: 'https://tweakers.net/nieuws/231452/nintendo-switch-2-aangekondigd',
    imageUrl: 'https://placehold.co/800x400/E60012/white?text=Switch+2',
    publishedAt: generateDate(0, 4, 45),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '6',
    title: 'Google Pixel 9a gelanceerd: betaalbare AI-smartphone voor €549',
    summary: 'Google presenteert de Pixel 9a met Tensor G4-chip, 48 MP camera en 7 jaar software-updates. De telefoon kost €549 in Europa. // Bron: https://store.google.com/product/pixel_9a',
    content: '',
    url: 'https://tweakers.net/nieuws/231451/google-pixel-9a',
    imageUrl: 'https://placehold.co/800x400/4285F4/white?text=Pixel+9a',
    publishedAt: generateDate(0, 3, 20),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '7',
    title: 'Microsoft rolt Windows 11 24H2 uit: nieuwe AI-functies en betere prestaties',
    summary: 'De grote Windows 11-update 24H2 is beschikbaar met Copilot-integratie, verbeterd energiebeheer en snellere opstarttijden.',
    content: '',
    url: 'https://tweakers.net/nieuws/231450/windows-11-24h2',
    imageUrl: 'https://placehold.co/800x400/00A4EF/white?text=Windows+11',
    publishedAt: generateDate(0, 2, 10),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '8',
    title: 'Tesla Model Y krijgt facelift: nieuw interieur en groter bereik',
    summary: 'Tesla vernieuwt de Model Y met een nieuw stuur, 7-inch passagiersscherm en een bereik tot 600 km. Prijzen starten vanaf €44.990.',
    content: '',
    url: 'https://tweakers.net/nieuws/231449/tesla-model-y-facelift',
    imageUrl: 'https://placehold.co/800x400/E82127/white?text=Tesla+Model+Y',
    publishedAt: generateDate(1, 14, 30),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '9',
    title: 'Ziggo verhoogt internetsnelheden naar 2 Gbit/s zonder meerprijs',
    summary: 'Ziggo kondigt aan dat alle klanten met het snelste abonnement kosteloos worden geupgraded naar 2 Gbit/s download. De upgrade begint in april.',
    content: '',
    url: 'https://tweakers.net/nieuws/231448/ziggo-2-gbps',
    imageUrl: 'https://placehold.co/800x400/E5007D/white?text=Ziggo+2Gbps',
    publishedAt: generateDate(1, 12, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '10',
    title: 'EU keurt AI Act goed: nieuwe regels voor kunstmatige intelligentie',
    summary: 'Het Europees Parlement stemt voor de AI Act, de eerste uitgebreide AI-wetgeving ter wereld. Bedrijven krijgen twee jaar om aan de regels te voldoen.',
    content: '',
    url: 'https://tweakers.net/nieuws/231447/eu-ai-act',
    imageUrl: 'https://placehold.co/800x400/003399/white?text=EU+AI+Act',
    publishedAt: generateDate(1, 10, 15),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '11',
    title: '[ONBEVESTIGD] Steam Deck OLED 2 gelekt: groter scherm en snellere processor',
    summary: 'Valve werkt mogelijk aan een opvolger van de Steam Deck OLED met een 7,4-inch scherm en AMD Zen 5-processor, volgens onbevestigde geruchten.',
    content: '',
    url: 'https://tweakers.net/nieuws/231446/steam-deck-oled-2',
    imageUrl: 'https://placehold.co/800x400/1B2838/white?text=Steam+Deck+2',
    publishedAt: generateDate(1, 8, 0),
    category: 'nieuws',
    source: 'Tweakers (Mock)',
    author: '',
  },
  {
    id: '12',
    title: 'KPN biedt glasvezel aan tot 8 Gbit/s in grote steden',
    summary: 'KPN start met het aanbieden van 8 Gbit/s glasvezelabonnementen in Amsterdam, Rotterdam en Den Haag. De prijs bedraagt €69,95 per maand.',
    content: '',
    url: 'https://tweakers.net/nieuws/231445/kpn-8-gbps',
    imageUrl: 'https://placehold.co/800x400/009A44/white?text=KPN+8Gbps',
    publishedAt: generateDate(2, 16, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '13',
    title: 'OpenAI lanceert GPT-5: multimodaal en realtime spraak',
    summary: 'OpenAI onthult GPT-5 met verbeterde redeneercapaciteiten, realtime spraakinteractie en native multimodale input voor tekst, beeld en video.',
    content: '',
    url: 'https://tweakers.net/nieuws/231444/openai-gpt-5',
    imageUrl: 'https://placehold.co/800x400/10A37F/white?text=GPT-5',
    publishedAt: generateDate(2, 14, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '14',
    title: 'Sonos onthult Arc Ultra soundbar met Dolby Atmos en ruimtelijk geluid',
    summary: 'De nieuwe Sonos Arc Ultra ondersteunt Dolby Atmos, heeft 14 drivers en biedt vernieuwde Sound Motion-technologie. Prijs: €999. // Bron: https://www.sonos.com',
    content: '',
    url: 'https://tweakers.net/nieuws/231443/sonos-arc-ultra',
    imageUrl: 'https://placehold.co/800x400/000000/white?text=Sonos+Arc+Ultra',
    publishedAt: generateDate(3, 12, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '15',
    title: 'DJI Mini 4 Pro: 4K/60fps drone weegt slechts 249 gram',
    summary: 'DJI Mini 4 Pro met 1/1.3-inch sensor, 4K/60fps HDR video en 34 minuten vliegtijd. De drone blijft onder de 250-gramgrens. // Bron: https://www.dji.com/mini-4-pro',
    content: '',
    url: 'https://tweakers.net/nieuws/231442/dji-mini-4-pro',
    imageUrl: 'https://placehold.co/800x400/000000/white?text=DJI+Mini+4+Pro',
    publishedAt: generateDate(3, 10, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '16',
    title: 'SpaceX Starlink nu beschikbaar in Nederland vanaf €50 per maand',
    summary: 'Starlink-internet is beschikbaar in Nederland met downloadsnelheden tot 220 Mbit/s. Het abonnement kost €50 per maand plus €225-€349 voor de hardware. // Bron: https://www.starlink.com',
    content: '',
    url: 'https://tweakers.net/nieuws/231441/starlink-nederland',
    imageUrl: 'https://placehold.co/800x400/0055D4/white?text=Starlink+NL',
    publishedAt: generateDate(4, 8, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '17',
    title: 'Canon EOS R1 officieel: het snelste autofocussysteem ooit',
    summary: 'Canon presenteert de EOS R1 met een nieuw 24,2 MP full-frame sensor, AI-gestuurd autofocussysteem en 40 fps continue opname.',
    content: '',
    url: 'https://tweakers.net/nieuws/231440/canon-eos-r1',
    imageUrl: 'https://placehold.co/800x400/000000/white?text=Canon+EOS+R1',
    publishedAt: generateDate(5, 6, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '18',
    title: 'Xiaomi 15 Ultra met Leica-camera komt naar Europa voor €1.399',
    summary: 'Xiaomi brengt de 15 Ultra met Leica Summilux-camera en Snapdragon 8 Elite naar de Europese markt. De telefoon is vanaf april verkrijgbaar.',
    content: '',
    url: 'https://tweakers.net/nieuws/231439/xiaomi-15-ultra-europa',
    imageUrl: 'https://placehold.co/800x400/FF6900/white?text=Xiaomi+15+Ultra',
    publishedAt: generateDate(5, 4, 0),
    category: 'nieuws',
    source: 'Tweakers',
    author: '',
  },
  // ─── Reviews ─────────────────────────────────────────────────────────────────
  {
    id: '19',
    title: 'Samsung Galaxy S25 Ultra review: het ultieme vlaggenschip getest',
    summary: 'De Galaxy S25 Ultra imponeert met zijn Snapdragon 8 Elite-chip, 200 MP camera en 6,9-inch Dynamic AMOLED-scherm. Wij testten alle aspecten.',
    content: '',
    url: 'https://tweakers.net/reviews/14567/samsung-galaxy-s25-ultra',
    imageUrl: 'https://placehold.co/800x400/1A73E8/white?text=S25+Ultra+Review',
    publishedAt: generateDate(0, 11, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '20',
    title: 'Apple MacBook Pro 14" M4 Pro review: krachtigste laptop ooit?',
    summary: 'De MacBook Pro met M4 Pro-chip biedt ongekende prestaties in een compact formaat. Wij testten de snelheid, batterijduur en het scherm.',
    content: '',
    url: 'https://tweakers.net/reviews/14566/macbook-pro-14-m4-pro',
    imageUrl: 'https://placehold.co/800x400/555555/white?text=MacBook+Pro+M4',
    publishedAt: generateDate(0, 9, 30),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '21',
    title: 'Sony WH-1000XM6 review: de beste noise-cancelling koptelefoon',
    summary: 'Sony verbetert de noise-cancelling, het geluid en het draagcomfort aanzienlijk. De XM6 zet opnieuw de standaard in zijn klasse.',
    content: '',
    url: 'https://tweakers.net/reviews/14565/sony-wh-1000xm6',
    imageUrl: 'https://placehold.co/800x400/1A1A1A/white?text=WH-1000XM6+Review',
    publishedAt: generateDate(1, 9, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '22',
    title: 'LG OLED G4 65" review: de beste tv die je kunt kopen',
    summary: 'De LG OLED G4 levert perfecte zwartwaarden, hoge piekhelderheid en fantastisch HDR-beeld. Wij testten hem in onze woonkamer.',
    content: '',
    url: 'https://tweakers.net/reviews/14564/lg-oled-g4-65',
    imageUrl: 'https://placehold.co/800x400/003087/white?text=LG+OLED+G4',
    publishedAt: generateDate(2, 14, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '23',
    title: 'Nvidia GeForce RTX 5080 Founders Edition review: snelste GPU onder €1.200',
    summary: 'De RTX 5080 biedt uitstekende 4K-gamingprestaties en DLSS 4 frame generation. Wij testten hem in 20 games.',
    content: '',
    url: 'https://tweakers.net/reviews/14563/nvidia-rtx-5080-fe',
    imageUrl: 'https://placehold.co/800x400/76B900/white?text=RTX+5080+Review',
    publishedAt: generateDate(2, 11, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '24',
    title: 'AMD Ryzen 7 9800X3D review: de beste gaming-processor',
    summary: 'Met 3D V-Cache en Zen 5-architectuur is de Ryzen 7 9800X3D onverslaanbaar in games. Wij benchmarkten hem uitgebreid.',
    content: '',
    url: 'https://tweakers.net/reviews/14562/amd-ryzen-7-9800x3d',
    imageUrl: 'https://placehold.co/800x400/ED1C24/white?text=9800X3D+Review',
    publishedAt: generateDate(2, 8, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '25',
    title: '[ONBEVESTIGD] Apple Watch Ultra 3 review: de ultieme sporthorloge?',
    summary: 'Onbevestigde geruchten over de Ultra 3 suggereren mogelijke verbeteringen aan het scherm en sensoren. (Let op: Placeholder data voor mock doeleinden)',
    content: '',
    url: 'https://tweakers.net/reviews/14561/apple-watch-ultra-3',
    imageUrl: 'https://placehold.co/800x400/555555/white?text=Watch+Ultra+3',
    publishedAt: generateDate(3, 15, 0),
    category: 'reviews',
    source: 'Tweakers (Mock)',
    author: '',
  },
  {
    id: '26',
    title: 'Samsung Odyssey OLED G8 34" review: perfecte gaming-monitor',
    summary: 'De Odyssey OLED G8 combineert een 34-inch ultrawide OLED-paneel met 175 Hz en 0,03 ms responstijd. Ideaal voor gamers.',
    content: '',
    url: 'https://tweakers.net/reviews/14560/samsung-odyssey-oled-g8-34',
    imageUrl: 'https://placehold.co/800x400/1A73E8/white?text=Odyssey+G8+Review',
    publishedAt: generateDate(3, 12, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '27',
    title: 'Dyson V15s Detect Submarine review: stofzuiger en dweil in een',
    summary: 'Dyson combineert stofzuigen en dweilen in de V15s Detect Submarine. Wij testten of het echt werkt op harde vloeren.',
    content: '',
    url: 'https://tweakers.net/reviews/14559/dyson-v15s-detect-submarine',
    imageUrl: 'https://placehold.co/800x400/CC7722/white?text=Dyson+V15s',
    publishedAt: generateDate(3, 9, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '28',
    title: 'Dell XPS 16 2025 review: prachtig OLED-scherm, maar warm',
    summary: 'De Dell XPS 16 heeft een schitterend 4K OLED-scherm en snelle Core Ultra 9 processor, maar wordt onder belasting behoorlijk warm.',
    content: '',
    url: 'https://tweakers.net/reviews/14558/dell-xps-16-2025',
    imageUrl: 'https://placehold.co/800x400/007DB8/white?text=Dell+XPS+16',
    publishedAt: generateDate(4, 16, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '29',
    title: 'Roborock S8 MaxV Ultra review: de slimste robotstofzuiger',
    summary: 'De Roborock S8 MaxV Ultra heeft een uitschuifbare mop, sterke zuigkracht en geavanceerde objectherkenning. Wij testten hem twee weken lang.',
    content: '',
    url: 'https://tweakers.net/reviews/14557/roborock-s8-maxv-ultra',
    imageUrl: 'https://placehold.co/800x400/1A1A1A/white?text=Roborock+S8+MaxV',
    publishedAt: generateDate(4, 13, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
  {
    id: '30',
    title: 'Corsair K100 Air review: een ultra-dun mechanisch toetsenbord',
    summary: 'Corsair maakt met het K100 Air een zeer dun mechanisch toetsenbord met Cherry MX Ultra Low Profile-switches. Premium kwaliteit voor €259. // Bron: https://www.corsair.com',
    content: '',
    url: 'https://tweakers.net/reviews/14556/corsair-k100-air',
    imageUrl: 'https://placehold.co/800x400/FFD700/black?text=K100+Air+Review',
    publishedAt: generateDate(5, 10, 0),
    category: 'reviews',
    source: 'Tweakers',
    author: '',
  },
];

export function getMockArticles(): Article[] {
  return mockArticles;
}

export function getMockArticlesByCategory(category: 'nieuws' | 'reviews'): Article[] {
  return mockArticles.filter(article => article.category === category);
}
