const fs = require('fs');
const path = require('path');

const imageMap = {
  // ═══ SMARTPHONES ═══
  "Samsung Galaxy S25 Ultra":  "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-ultra5g-1.jpg",
  "Samsung Galaxy S25+":       "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s25-plus5g-1.jpg",
  "Samsung Galaxy S25":        "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s255g-1.jpg",
  "Samsung Galaxy S24 Ultra":  "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24-ultra5g-1.jpg",
  "Samsung Galaxy S24+":       "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s24plus5g-1.jpg",
  "Samsung Galaxy S24":        "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s245g-1.jpg",
  "Samsung Galaxy Z Fold 6":   "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-fold6-1.jpg",
  "Samsung Galaxy Z Flip 6":   "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-z-flip6-1.jpg",
  "Samsung Galaxy A55":        "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a555g-1.jpg",
  "Samsung Galaxy A35":        "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-a355g-1.jpg",
  "iPhone 16 Pro Max":         "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-pro-max-1.jpg",
  "iPhone 16 Pro":             "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-pro-1.jpg",
  "iPhone 16":                 "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16-1.jpg",
  "iPhone 16e":                "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-16e-1.jpg",
  "iPhone 15 Pro Max":         "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-max-1.jpg",
  "iPhone 15 Pro":             "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-pro-1.jpg",
  "iPhone 15":                 "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-15-1.jpg",
  "iPhone 14":                 "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-1.jpg",
  "Google Pixel 9 Pro XL":     "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-xl-1.jpg",
  "Google Pixel 9 Pro":        "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-pro-1.jpg",
  "Google Pixel 9":            "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-9-1.jpg",
  "Google Pixel 8a":           "https://fdn2.gsmarena.com/vv/pics/google/google-pixel-8a-1.jpg",
  "OnePlus 13":                "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-13-1.jpg",
  "OnePlus 12":                "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-12-1.jpg",
  "OnePlus Nord 4":            "https://fdn2.gsmarena.com/vv/pics/oneplus/oneplus-nord4-1.jpg",

  // ═══ TABLETS ═══
  "iPad Pro 13-inch M4":          "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-13-2024-1.jpg",
  "iPad Pro 11-inch M4":          "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-pro-11-2024-1.jpg",
  "iPad Air 13-inch M3":          "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air-13-2024-1.jpg",
  "iPad Air 11-inch M3":          "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-air-11-2024-1.jpg",
  "iPad mini A17 Pro":            "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-mini-7-2024-1.jpg",
  "iPad 10th generation":         "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-10-2022-1.jpg",
  "iPad 9th generation":          "https://fdn2.gsmarena.com/vv/pics/apple/apple-ipad-9-2021-1.jpg",
  "Samsung Galaxy Tab S10 Ultra": "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s10-ultra-1.jpg",
  "Samsung Galaxy Tab S10+":      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s10-plus-1.jpg",
  "Samsung Galaxy Tab S9 FE+":    "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-s9-fe-plus-1.jpg",
  "Samsung Galaxy Tab A9+":       "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-tab-a9-plus-1.jpg",
  "OPPO Pad 3 Pro":               "https://fdn2.gsmarena.com/vv/pics/oppo/oppo-pad-3-pro-1.jpg",
  "Xiaomi Pad 7 Pro":             "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-pad-7-pro-1.jpg",
  "Xiaomi Pad 6":                 "https://fdn2.gsmarena.com/vv/pics/xiaomi/xiaomi-pad-6-1.jpg",
  "Lenovo Tab P12":               "https://fdn2.gsmarena.com/vv/pics/lenovo/lenovo-tab-p12-1.jpg",
  "Lenovo Tab M10 Plus":          "https://fdn2.gsmarena.com/vv/pics/lenovo/lenovo-tab-m10-plus-gen3-1.jpg",
  "Microsoft Surface Pro 11":     "https://fdn2.gsmarena.com/vv/pics/microsoft/microsoft-surface-pro-11-1.jpg",
  "Microsoft Surface Go 4":       "https://fdn2.gsmarena.com/vv/pics/microsoft/microsoft-surface-go-4-1.jpg",
  "Amazon Fire HD 10":            "https://fdn2.gsmarena.com/vv/pics/amazon/amazon-fire-hd-10-2023-1.jpg",
  "Amazon Fire HD 8":             "https://fdn2.gsmarena.com/vv/pics/amazon/amazon-fire-hd-8-2022-1.jpg",

  // ═══ LAPTOPS ═══
  "Apple MacBook Pro 14-inch M4":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp14-m3-pro-space-black-select-202311?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple MacBook Pro 16-inch M4":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp16-m3-pro-space-black-select-202311?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple MacBook Air 13-inch M4":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba13-m3-midnight-select-202402?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple MacBook Air 15-inch M4":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba15-m3-midnight-select-202402?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple MacBook Air 13-inch M3":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba13-m3-starlight-select-202402?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Dell XPS 15":                   "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/black/notebook-xps-9530-black-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell XPS 13":                   "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-13-9340/media-gallery/platinum/notebook-xps-9340-platinum-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell XPS 17":                   "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-17-9730/media-gallery/black/notebook-xps-9730-black-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell Inspiron 15":              "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/inspiron-notebooks/inspiron-15-3530/media-gallery/notebook-inspiron-3530-gallery-1.psd?fmt=png-alpha&wid=800",
  "HP Spectre x360":               "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knowledgebase/c08173167.png",
  "HP Envy 16":                    "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knowledgebase/c08370989.png",
  "HP Pavilion 15":                "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knowledgebase/c07704459.png",
  "Lenovo ThinkPad X1 Carbon":     "https://p3-ofp.static.pub/ShareResource/na/subseries/hero/20230801/thinkpad-x1-carbon-gen11-hero.png",
  "Lenovo ThinkPad T14s":          "https://p3-ofp.static.pub/ShareResource/na/subseries/hero/20230201/thinkpad-t14s-gen4-hero.png",
  "Lenovo Yoga 9i":                "https://p3-ofp.static.pub/ShareResource/na/subseries/hero/20230401/yoga-9i-gen8-hero.png",
  "Lenovo IdeaPad 5":              "https://p3-ofp.static.pub/ShareResource/na/subseries/hero/20230201/ideapad-5-gen8-hero.png",
  "ASUS ROG Zephyrus G16":         "https://dlcdnwebimgs.asus.com/gain/GA605WV/W1T/1M.jpg",
  "ASUS ROG Strix G16":            "https://dlcdnwebimgs.asus.com/gain/G614JV/W1T/1M.jpg",
  "ASUS ZenBook 14":               "https://dlcdnwebimgs.asus.com/gain/UX3405MA/W1T/1M.jpg",
  "ASUS VivoBook 15":              "https://dlcdnwebimgs.asus.com/gain/X1504ZA/W1T/1M.jpg",
  "Microsoft Surface Laptop 6":    "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW1lQaV?ver=1d37",
  "Microsoft Surface Laptop Go 3": "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RW15XNI?ver=e58b",
  "Acer Swift Go 14":              "https://static.acer.com/up/Resource/Acer/Laptops/Swift_Go_14/Subpage/20230301/swift-go-14-hero.png",
  "Acer Aspire 5":                 "https://static.acer.com/up/Resource/Acer/Laptops/Aspire_5/Subpage/20230901/aspire-5-hero.png",
  "MSI Prestige 14":               "https://asset.msi.com/resize/image/global/product/product_prestige_14_main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",

  // ═══ DESKTOPS ═══
  "Apple Mac Studio M2 Ultra": "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-select-202306?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple Mac mini M4":         "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-hero-202411?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Apple Mac mini M4 Pro":     "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-pro-hero-202411?wid=904&hei=840&fmt=jpeg&qlt=90",
  "Dell XPS Desktop":          "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/xps-desktops/xps-8960/media-gallery/desktop-xps-8960-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell Inspiron Desktop":     "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/desktops/inspiron-desktops/inspiron-3030-sff/media-gallery/desktop-inspiron-3030s-gallery-1.psd?fmt=png-alpha&wid=800",
  "HP Envy Desktop":           "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knowledgebase/c08578225.png",
  "HP Pavilion Desktop":       "https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knowledgebase/c08508461.png",
  "Lenovo ThinkCentre M90q":   "https://p3-ofp.static.pub/ShareResource/na/products/hero/20220101/thinkcenter-m90q-gen3-hero.png",
  "Lenovo IdeaCentre 5":       "https://p3-ofp.static.pub/ShareResource/na/products/hero/20230101/ideacentre-5-hero.png",
  "ASUS ROG Strix G35":        "https://dlcdnwebimgs.asus.com/gain/G35DX/W1T/1M.jpg",
  "ASUS ExpertCenter D7":      "https://dlcdnwebimgs.asus.com/gain/D700TC/W1T/1M.jpg",
  "MSI MEG Trident X2":        "https://asset.msi.com/resize/image/global/product/product_MEG_Trident_X2_main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "MSI Codex R":               "https://asset.msi.com/resize/image/global/product/product_Codex_R_main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "Acer Aspire TC":            "https://static.acer.com/up/Resource/Acer/Desktops/Aspire_TC/Subpage/20230601/aspire-tc-hero.png",
  "Intel NUC 13 Pro":          "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2023-01/nuc-13-pro-kit-rnpd.png",

  // ═══ MONITOREN ═══
  "LG UltraGear 27GP950 4K":    "https://www.lg.com/nl/images/monitoren/md07542339/gallery/medium01.jpg",
  "LG UltraGear 32GQ950 4K":    "https://www.lg.com/nl/images/monitoren/md07541823/gallery/medium01.jpg",
  "LG UltraFine 5K":            "https://www.lg.com/nl/images/monitoren/md07507087/gallery/medium01.jpg",
  "Samsung Odyssey G9 49-inch": "https://images.samsung.com/nl/monitors/products/odyssey-g9-49-inch-dual-qhd-curved-gaming-monitor/LS49CG954SUXEN/gallery/nl-odyssey-g9-ls49cg954suxen-536272534.jpg",
  "Samsung Odyssey G7 32-inch": "https://images.samsung.com/nl/monitors/products/odyssey-g7-32-inch-qhd-curved-gaming-monitor/LS32BG702EUXEN/gallery/nl-odyssey-g7-ls32bg702euxen-535006047.jpg",
  "Samsung Smart Monitor M8":   "https://images.samsung.com/nl/monitors/products/smart-monitor-m8-32-inch-4k-uhd-monitor/LS32CM801UUXEN/gallery/nl-smart-monitor-m8-32-ls32cm801uuxen-534706012.jpg",
  "Dell UltraSharp U2723QE":    "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/peripherals/monitors/u-series/u2723qe/media-gallery/monitor-u-2723qe-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell UltraSharp U3223QE":    "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/peripherals/monitors/u-series/u3223qe/media-gallery/monitor-u-3223qe-gallery-1.psd?fmt=png-alpha&wid=800",
  "Dell S2722DGM 165Hz":        "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/peripherals/monitors/s-series/s2722dgm/media-gallery/monitor-s-2722dgm-gallery-1.psd?fmt=png-alpha&wid=800",
  "ASUS ROG Swift PG27UQR":     "https://dlcdnwebimgs.asus.com/gain/PG27UQR/W1T/1M.jpg",
  "ASUS ProArt PA279CV":        "https://dlcdnwebimgs.asus.com/gain/PA279CV/W1T/1M.jpg",
  "ASUS TUF Gaming VG27AQ":     "https://dlcdnwebimgs.asus.com/gain/VG27AQ/W1T/1M.jpg",
  "BenQ EX2710U 4K":            "https://monitor.benq.com/content/dam/benq/products/monitor/EX2710U/gallery/benq-mobiuz-monitor-ex2710u-product-photo.jpg",
  "BenQ PD2705U 4K":            "https://monitor.benq.com/content/dam/benq/products/monitor/PD2705U/gallery/benq-designer-monitor-pd2705u-product-photo.jpg",
  "Acer Predator X32 FP":       "https://static.acer.com/up/Resource/Acer/Monitors/Predator_X32_FP/Subpage/20230801/predator-x32-fp-hero.png",
  "Acer Nitro XV272U":          "https://static.acer.com/up/Resource/Acer/Monitors/Nitro_XV2/Subpage/20220701/nitro-xv272-hero.png",
  "Philips 27E1N8900 OLED":     "https://images.philips.com/is/image/philipsconsumer/27e1n8900_00-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Philips 279P1 4K":           "https://images.philips.com/is/image/philipsconsumer/279p1leb_00-nl-nl?wid=800&hei=800&fmt=jpeg",
  "MSI Optix MAG274QRF-QD":     "https://asset.msi.com/resize/image/global/product/product_MAG274QRF-QD.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "ViewSonic ColorPro VP2776":  "https://www.viewsonic.com/nl/products/lcd/images/VP2776-main.jpg",

  // ═══ GRAFISCHE KAARTEN ═══
  "NVIDIA GeForce RTX 4090":         "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4090/geforce-rtx-4090-shop-600-p@2x.png",
  "NVIDIA GeForce RTX 4080 Super":   "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4080-super/geforce-rtx-4080-super-shop-600-p@2x.png",
  "NVIDIA GeForce RTX 4070 Ti Super":"https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4070-ti-super/geforce-rtx-4070-ti-super-shop-600-p@2x.png",
  "NVIDIA GeForce RTX 4070 Super":   "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4070-super/geforce-rtx-4070-super-shop-600-p@2x.png",
  "NVIDIA GeForce RTX 4060 Ti":      "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4060-ti/geforce-rtx-4060ti-shop-600-p@2x.png",
  "NVIDIA GeForce RTX 4060":         "https://www.nvidia.com/content/dam/en-zz/Solutions/geforce/ada/rtx-4060/geforce-rtx-4060-shop-600-p@2x.png",
  "AMD Radeon RX 7900 XTX":          "https://www.amd.com/system/files/styles/992px/private/2022-11/1217101-amd-radeon-rx-7900-xtx-pib-1260x709-1260x709.png",
  "AMD Radeon RX 7900 XT":           "https://www.amd.com/system/files/styles/992px/private/2022-11/1217099-amd-radeon-rx-7900-xt-pib-1260x709-1260x709.png",
  "AMD Radeon RX 7800 XT":           "https://www.amd.com/system/files/styles/992px/private/2023-08/1215971-radeon-rx-7800-xt-pib-1260x709.png",
  "AMD Radeon RX 7700 XT":           "https://www.amd.com/system/files/styles/992px/private/2023-08/1215971-radeon-rx-7700-xt-pib-1260x709.png",
  "AMD Radeon RX 7600":              "https://www.amd.com/system/files/styles/992px/private/2023-05/1215971-radeon-rx-7600-pib-1260x709.png",
  "Intel Arc A770":                  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-09/arc-a770-limited-edition-front-rwd.png",
  "Intel Arc A750":                  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-09/arc-a750-limited-edition-front-rwd.png",
  "Intel Arc A580":                  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2023-09/arc-a580-front-rwd.png",
  "ASUS ROG Strix RTX 4080":         "https://dlcdnwebimgs.asus.com/gain/ROG-STRIX-RTX4080-O16G-GAMING/W1T/1M.jpg",

  // ═══ PROCESSORS ═══
  "Intel Core i9-14900K":     "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-11/boxed-processor-sku-14900k-16x9.png",
  "Intel Core i7-14700K":     "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-11/boxed-processor-sku-14700k-16x9.png",
  "Intel Core i5-14600K":     "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-11/boxed-processor-sku-14600k-16x9.png",
  "Intel Core i5-14400":      "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-11/boxed-processor-sku-14400-16x9.png",
  "Intel Core i3-14100":      "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2022-11/boxed-processor-sku-14100-16x9.png",
  "AMD Ryzen 9 9950X":        "https://www.amd.com/system/files/styles/992px/private/2024-07/2403022-amd-ryzen-9-9950x-PIB-1260x709.png",
  "AMD Ryzen 9 9900X":        "https://www.amd.com/system/files/styles/992px/private/2024-07/2403022-amd-ryzen-9-9900x-PIB-1260x709.png",
  "AMD Ryzen 7 9700X":        "https://www.amd.com/system/files/styles/992px/private/2024-07/2403022-amd-ryzen-7-9700x-PIB-1260x709.png",
  "AMD Ryzen 5 9600X":        "https://www.amd.com/system/files/styles/992px/private/2024-07/2403022-amd-ryzen-5-9600x-PIB-1260x709.png",
  "AMD Ryzen 7 7800X3D":      "https://www.amd.com/system/files/styles/992px/private/2023-01/2403022-amd-ryzen-7-7800x3d-PIB-1260x709.png",
  "AMD Ryzen 5 7600X":        "https://www.amd.com/system/files/styles/992px/private/2022-09/2403022-amd-ryzen-5-7600x-PIB-1260x709.png",
  "AMD Ryzen 5 7500F":        "https://www.amd.com/system/files/styles/992px/private/2023-05/2403022-amd-ryzen-5-7500f-PIB-1260x709.png",
  "Intel Core Ultra 9 285K":  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2024-10/boxed-processor-sku-285k-16x9.png",
  "Intel Core Ultra 7 265K":  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2024-10/boxed-processor-sku-265k-16x9.png",
  "Intel Core Ultra 5 245K":  "https://www.intel.com/content/dam/www/central-libraries/us/en/images/2024-10/boxed-processor-sku-245k-16x9.png",

  // ═══ MOERBORDEN ═══
  "ASUS ROG Maximus Z890 Hero":    "https://dlcdnwebimgs.asus.com/gain/ROG-MAXIMUS-Z890-HERO/W1T/1M.jpg",
  "ASUS ROG Strix Z890-E":         "https://dlcdnwebimgs.asus.com/gain/ROG-STRIX-Z890-E-GAMING-WIFI/W1T/1M.jpg",
  "ASUS TUF Gaming Z890-Plus":     "https://dlcdnwebimgs.asus.com/gain/TUF-GAMING-Z890-PLUS-WIFI/W1T/1M.jpg",
  "ASUS Prime Z890-P":             "https://dlcdnwebimgs.asus.com/gain/PRIME-Z890-P-WIFI/W1T/1M.jpg",
  "MSI MEG Z890 ACE":              "https://asset.msi.com/resize/image/global/product/product_MEG-Z890-ACE-main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "MSI MPG Z890 Carbon WiFi":      "https://asset.msi.com/resize/image/global/product/product_MPG-Z890-CARBON-WIFI-main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "MSI MAG Z890 Tomahawk WiFi":    "https://asset.msi.com/resize/image/global/product/product_MAG-Z890-TOMAHAWK-WIFI-main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "Gigabyte Z890 AORUS Master":    "https://static.gigabyte.com/StaticFile/Image/Global/de8c7aed1d2e75b614dda6e5e40e2e9c/Product/34076/png/800",
  "Gigabyte Z890 AORUS Elite":     "https://static.gigabyte.com/StaticFile/Image/Global/de8c7aed1d2e75b614dda6e5e40e2e9d/Product/34075/png/800",
  "Gigabyte Z890 UD":              "https://static.gigabyte.com/StaticFile/Image/Global/de8c7aed1d2e75b614dda6e5e40e2e9e/Product/34074/png/800",
  "ASRock Z890 Taichi":            "https://pg.asrock.com/mb/photo/Z890%20Taichi(L3).png",
  "ASRock Z890 Steel Legend":      "https://pg.asrock.com/mb/photo/Z890%20Steel%20Legend%20WiFi(L2).png",
  "ASUS ROG Crosshair X870E Hero": "https://dlcdnwebimgs.asus.com/gain/ROG-CROSSHAIR-X870E-HERO/W1T/1M.jpg",
  "MSI MPG X870E Carbon WiFi":     "https://asset.msi.com/resize/image/global/product/product_MPG-X870E-CARBON-WIFI-main.png62405b38c58fe0f07fcef2367d8a9ba1/1024.png",
  "Gigabyte X870E AORUS Master":   "https://static.gigabyte.com/StaticFile/Image/Global/de8c7aed1d2e75b614dda6e5e40e2e9f/Product/33750/png/800",

  // ═══ GEHEUGEN ═══
  "Corsair Dominator Titanium DDR5-6600":   "https://www.corsair.com/medias/sys_master/images/images/hb4/h2d/9617416822814/CM5S32GX5M2B6600C32-Gallery-Dominator-Titanium-DDR5-Black-01.png",
  "Corsair Vengeance RGB DDR5-6000":        "https://www.corsair.com/medias/sys_master/images/images/hd2/hf3/9617412595742/CMH32GX5M2B6000C30K-Gallery-Vengeance-RGB-DDR5-Black-01.png",
  "Corsair Vengeance DDR5-5600":            "https://www.corsair.com/medias/sys_master/images/images/hd4/hf5/9618133254174/CMK32GX5M2B5600C36-Gallery-Vengeance-DDR5-Black-01.png",
  "G.Skill Trident Z5 RGB DDR5-6400":      "https://www.gskill.com/img/1/F5-6400J3239G16GX2-TZ5RK.png",
  "G.Skill Trident Z5 DDR5-6000":          "https://www.gskill.com/img/1/F5-6000J3636F16GX2-TZ5K.png",
  "G.Skill Ripjaws S5 DDR5-5600":          "https://www.gskill.com/img/1/F5-5600J3636D16GX2-RS5K.png",
  "Kingston Fury Beast DDR5-6000":         "https://media.kingston.com/kingston/product/ktc-product-fury-ram-beast-ddr5-rgb-2-lg.png",
  "Kingston Fury Renegade DDR5-7200":      "https://media.kingston.com/kingston/product/ktc-product-fury-ram-renegade-ddr5-rgb-2-lg.png",
  "TeamGroup T-Force Delta RGB DDR5-6000": "https://www.teamgroupinc.com/data/upload/spec/product/3000/5d1b9aeacc7e6.png",
  "TeamGroup T-Force Vulcan DDR5-5600":    "https://www.teamgroupinc.com/data/upload/spec/product/3000/5d1b9aeacc7e7.png",
  "Crucial DDR5-5600 32GB":                "https://www.crucial.com/content/dam/crucial/dram-products/crucial-ddr5-desktop-ram.png",
  "Crucial Pro DDR5-6000 32GB":            "https://www.crucial.com/content/dam/crucial/dram-products/crucial-pro-ddr5-desktop-ram.png",
  "Patriot Viper Venom DDR5-6000":         "https://www.patriotmemory.com/storage/PVV532G600C36K/PVV532G600C36K_main.jpg",
  "Silicon Power XPOWER DDR5-6000":        "https://www.silicon-power.com/web/imgs/product/SP064GXLWU600FDH_01.jpg",
  "ADATA XPG Lancer RGB DDR5-6000":        "https://www.adata.com/upload/products/SP/AX5U6000C3016G-DCLARBK_1.png",

  // ═══ OPSLAG ═══
  "Samsung 990 Pro 2TB":      "https://images.samsung.com/nl/memory-storage/990-pro/images/990-pro-nvme-m-2-ssd-front.jpg",
  "Samsung 990 Pro 1TB":      "https://images.samsung.com/nl/memory-storage/990-pro/images/990-pro-nvme-m-2-ssd-front.jpg",
  "Samsung 980 Pro 1TB":      "https://images.samsung.com/nl/memory-storage/980-pro/images/980-pro-nvme-m-2-ssd-front.jpg",
  "WD Black SN850X 2TB":      "https://www.westerndigital.com/content/dam/store/en-us/assets/products/internal-storage/wd-black-sn850x-nvme-ssd/gallery/wd-black-sn850x-nvme-ssd-heatsink-2tb-front.png",
  "WD Black SN850X 1TB":      "https://www.westerndigital.com/content/dam/store/en-us/assets/products/internal-storage/wd-black-sn850x-nvme-ssd/gallery/wd-black-sn850x-nvme-ssd-1tb-front.png",
  "WD Red SN700 1TB":         "https://www.westerndigital.com/content/dam/store/en-us/assets/products/internal-storage/wd-red-sn700-nvme-ssd/gallery/wd-red-sn700-nvme-ssd-1tb-front.png",
  "Crucial T700 2TB Gen5":    "https://www.crucial.com/content/dam/crucial/ssd-products/t700/crucial-t700-ssd.png",
  "Crucial P5 Plus 1TB":      "https://www.crucial.com/content/dam/crucial/ssd-products/p5-plus/crucial-p5-plus-ssd.png",
  "Kingston KC3000 2TB":      "https://media.kingston.com/kingston/product/ktc-product-ssd-kc3000-1-lg.png",
  "Kingston A400 480GB":      "https://media.kingston.com/kingston/product/ktc-product-ssd-a400-1-lg.png",
  "Seagate FireCuda 530 2TB": "https://www.seagate.com/www-content/product-content/firecuda/images/firecuda-530-ssd-pdp-hero.png",
  "Seagate Barracuda 1TB SSD":"https://www.seagate.com/www-content/product-content/barracuda-fam/barracuda-ssd/images/barracuda-ssd-pdp-hero.png",
  "Sabrent Rocket 4TB":       "https://sabrent.com/cdn/shop/products/SB-RKTQ-4TB-main.jpg",
  "ADATA XPG Sage 2TB":       "https://www.adata.com/upload/products/SP/ALEG-960M-1TCS_1.png",
  "Intel Optane P5810X 800GB":"https://www.intel.com/content/dam/www/central-libraries/us/en/images/2021-04/optane-p5810x-ssd-rwd.png",

  // ═══ TELEVISIES ═══
  "LG OLED C4 55-inch":           "https://www.lg.com/nl/images/televisies/md08003910/gallery/medium01.jpg",
  "LG OLED C4 65-inch":           "https://www.lg.com/nl/images/televisies/md08003912/gallery/medium01.jpg",
  "LG OLED G4 55-inch":           "https://www.lg.com/nl/images/televisies/md08003920/gallery/medium01.jpg",
  "LG OLED G4 65-inch":           "https://www.lg.com/nl/images/televisies/md08003922/gallery/medium01.jpg",
  "LG OLED M4 65-inch":           "https://www.lg.com/nl/images/televisies/md08003930/gallery/medium01.jpg",
  "Samsung OLED S90D 55-inch":    "https://images.samsung.com/nl/televisions-home-theater/tvs/oled-tvs/55-s90d-4k-oled-smart-tv-2024/TQ55S90DAUXXN/gallery/nl-oled-s90d-tq55s90dauxxn-537440888.jpg",
  "Samsung OLED S90D 65-inch":    "https://images.samsung.com/nl/televisions-home-theater/tvs/oled-tvs/65-s90d-4k-oled-smart-tv-2024/TQ65S90DAUXXN/gallery/nl-oled-s90d-tq65s90dauxxn-537440889.jpg",
  "Samsung QN90D 55-inch Neo QLED":"https://images.samsung.com/nl/televisions-home-theater/tvs/neo-qled-tvs/55-qn90d-neo-qled-4k-smart-tv-2024/TQ55QN90DAUXXN/gallery/nl-neo-qled-qn90d-tq55qn90dauxxn-thumb-537285059.jpg",
  "Samsung QN90D 65-inch Neo QLED":"https://images.samsung.com/nl/televisions-home-theater/tvs/neo-qled-tvs/65-qn90d-neo-qled-4k-smart-tv-2024/TQ65QN90DAUXXN/gallery/nl-neo-qled-qn90d-tq65qn90dauxxn-thumb-537285060.jpg",
  "Samsung Q80D 55-inch QLED":    "https://images.samsung.com/nl/televisions-home-theater/tvs/qled-tvs/55-q80d-qled-4k-smart-tv-2024/TQ55Q80DAUXXN/gallery/nl-qled-q80d-tq55q80dauxxn-thumb-537219701.jpg",
  "Sony OLED A80L 55-inch":       "https://www.sony.nl/image/5d02da5df552836db8845f16816db0e2?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=2515&hei=1415",
  "Sony OLED A80L 65-inch":       "https://www.sony.nl/image/6e13eb6ef663947ec9956g27927ec1f3?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=2515&hei=1415",
  "Sony A95L QD-OLED 55-inch":    "https://www.sony.nl/image/7f24fc7f0774a58fda0a67h38a38fd2g4?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=2515&hei=1415",
  "Sony XR-65A95L 65-inch":       "https://www.sony.nl/image/8g35gd8g1885b69geb1b78i49b49ge3h5?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=2515&hei=1415",
  "Philips OLED+908 55-inch":     "https://images.philips.com/is/image/philipsconsumer/55oled908_12-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Philips OLED+908 65-inch":     "https://images.philips.com/is/image/philipsconsumer/65oled908_12-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Philips PUS8808 55-inch MiniLED":"https://images.philips.com/is/image/philipsconsumer/55pus8808_12-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Philips PUS8908 65-inch MiniLED":"https://images.philips.com/is/image/philipsconsumer/65pus8908_12-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Hisense 65U8KQ MiniLED":       "https://consumer.hisense.eu/content/dam/hisense/de/consumer-electronics/television/4k/u8kq/gallery/U8KQ_65_Gallery.png",
  "TCL C845 55-inch MiniLED":     "https://www.tcl.com/euro/en/content/dam/consumer/products/tv/c845-mini-qled/c845-55-front.png",

  // ═══ AUDIO ═══
  "Sony WH-1000XM6":             "https://www.sony.nl/image/6145c1d32e1ac8e63a86c6d8a1d3b3e2?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Sony WF-1000XM6":             "https://www.sony.nl/image/7246d2e43f2bd9f74b97d7e9b2e4c4f3?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Apple AirPods Max":           "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-select-spacegray-202011?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple AirPods Pro 3":         "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MXK73?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple AirPods 4":             "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-4-select-202409?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple AirPods 4 ANC":         "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-4-anc-select-202409?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Samsung Galaxy Buds3 Pro":    "https://images.samsung.com/nl/galaxy-buds/products/galaxy-buds3-pro/images/galaxy-buds3-pro-sm-r630nzaaeub-thumb-538039524.jpg",
  "Samsung Galaxy Buds2 Pro":    "https://images.samsung.com/nl/galaxy-buds/products/galaxy-buds2-pro/images/galaxy-buds2-pro-bora-purple-front.jpg",
  "Bose QuietComfort Ultra":     "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc_ultra_headphones/product_silo_images/QC_Ultra_Headphones_Black_EC_Hero.jpg",
  "Bose QuietComfort Ultra Earbuds":"https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc_ultra_earbuds/product_silo_images/QC_Ultra_Earbuds_Black_EC_Hero.jpg",
  "Bose QuietComfort 45":        "https://assets.bose.com/content/dam/cloudassets/Bose_DAM/Web/consumer_electronics/global/products/headphones/qc45/product_silo_images/QC45_Headphones_Black_EC_Hero.png",
  "Sennheiser Momentum 4":       "https://assets.sennheiser.com/img/31248/x2_desktop_Momentum_4_Wireless_product_render_front_Graphite.png",
  "Sennheiser IE 200":           "https://assets.sennheiser.com/img/33124/x2_desktop_IE_200_product_render.png",
  "Sennheiser Accentum Plus":    "https://assets.sennheiser.com/img/35014/x2_desktop_ACCENTUM_Plus_Wireless_product_render_White.png",
  "JBL Tune 770NC":              "https://www.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw7038a5c7/JBL_TUNE770NC_Product%20Image_Hero_Blue.png",
  "JBL Tune 670NC":              "https://www.jbl.com/dw/image/v2/AAUJ_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw8e8f0b0b/JBL_TUNE670NC_Product%20Image_Hero_Black.png",
  "Nothing Ear 3":               "https://in.nothing.tech/cdn/shop/files/ear-3-white-pdp-1.png?v=1717483847&width=800",
  "Nothing Ear a":               "https://in.nothing.tech/cdn/shop/files/ear-a-yellow-pdp-1.png?v=1714027773&width=800",
  "Sony LinkBuds S":             "https://www.sony.nl/image/a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Sony WH-CH720N":              "https://www.sony.nl/image/b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",

  // ═══ GAMECONSOLES ═══
  "Sony PlayStation 5 Slim":   "https://gmedia.playstation.com/is/image/SIEPDC/ps5-slim-product-thumbnail-01-en-14sep23",
  "Sony PlayStation 5 Pro":    "https://gmedia.playstation.com/is/image/SIEPDC/ps5-pro-product-thumbnail-01-en-12sep24",
  "Microsoft Xbox Series X":   "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mRni?ver=f800",
  "Microsoft Xbox Series S":   "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4oIVa?ver=7411",
  "Nintendo Switch OLED":      "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_auto/c_scale,w_1200/ncom/en_US/switch/site-design-update/hardware/switch/nintendo-switch-oled-model-white-set/white-oled-set-front",
  "Nintendo Switch":           "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_auto/c_scale,w_1200/ncom/en_US/switch/site-design-update/hardware/switch/nintendo-switch-neon-blue-neon-red-joy-con-set/neon-set-front",
  "Nintendo Switch Lite":      "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_auto/c_scale,w_1200/ncom/en_US/switch/site-design-update/hardware/switch/nintendo-switch-lite-yellow/lite-yellow-front",
  "Valve Steam Deck 512GB":    "https://cdn.cloudflare.steamstatic.com/store/product/1675200/hero_capsule.jpg",
  "Valve Steam Deck OLED 1TB": "https://cdn.cloudflare.steamstatic.com/store/product/2376030/hero_capsule.jpg",
  "ASUS ROG Ally":             "https://dlcdnwebimgs.asus.com/gain/ROG-ALLY-RC71L/W1T/1M.jpg",

  // ═══ GAMING ═══
  "Sony DualSense Edge":           "https://gmedia.playstation.com/is/image/SIEPDC/dualsense-edge-controller-product-thumbnail-01-en-28sep22",
  "Sony DualSense":                "https://gmedia.playstation.com/is/image/SIEPDC/dualsense-controller-thumbnail-01-en-14sep21",
  "Xbox Series X Controller":      "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4NBO3?ver=c0c3",
  "Xbox Elite Controller Series 2":"https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mzWU?ver=1c58",
  "Nintendo Pro Controller":       "https://assets.nintendo.com/image/upload/f_auto/q_auto/dpr_auto/c_scale,w_600/ncom/en_US/products/accessories/switch/nintendo-switch-pro-controller/HAC_019_imgeHi_procontroller_image1600",
  "Logitech G Pro X Gaming Headset":"https://resource.logitech.com/w_800,c_limit,q_auto,f_auto/d_transparent.gif/content/dam/logitech/en/products/gaming-audio/g-pro-x-gaming-headset/gallery/g-pro-x-gaming-headset-gallery-1.png",
  "Razer BlackShark V2 Pro":       "https://assets3.razerzone.com/en-us/gaming-audio/razer-blackshark-v2-pro/headset-razer-blackshark-v2-pro-gallery-02.jpg",
  "Razer DeathAdder V3 Pro":       "https://assets3.razerzone.com/en-us/gaming-mice/razer-deathadder-v3-pro/mouse-razer-deathadder-v3-pro-gallery-02.jpg",
  "Razer Viper V3 Pro":            "https://assets3.razerzone.com/en-us/gaming-mice/razer-viper-v3-pro/mouse-razer-viper-v3-pro-gallery-01.jpg",
  "SteelSeries Arctis Nova Pro":   "https://media.steelseriescdn.com/thumbs/filer_public/06/22/0622e29a-67c0-4aeb-80aa-e4dd8476432c/arctis_nova_pro_wireless_main.png",
  "SteelSeries Apex Pro TKL":      "https://media.steelseriescdn.com/thumbs/filer_public/50/2c/502c2949-8e30-4f69-aadd-b2fd2f7b5a3c/apex_pro_tkl_2023_main.png",
  "Corsair K70 RGB Pro":           "https://www.corsair.com/medias/sys_master/images/images/hd1/hf8/8825133916190/CH-9109411-NA-Gallery-K70-RGB-PRO-01.png",
  "Corsair Ironclaw RGB":          "https://www.corsair.com/medias/sys_master/images/images/h67/h4e/8825100984350/CH-9307011-EU-Gallery-Ironclaw-RGB-01.png",
  "Secretlab Titan Evo 2024":      "https://cdn.secretlab.eu/wp-content/uploads/2023/11/titan-evo-2024-main-2.jpg",
  "Noblechairs Hero":              "https://noblechairs.com/cdn/shop/products/HERO-Series-Gaming-Chair-Black-Headrest-Cushion.jpg",

  // ═══ NETWERK ═══
  "ASUS RT-BE96U WiFi 7":        "https://dlcdnwebimgs.asus.com/gain/RT-BE96U/W1T/1M.jpg",
  "ASUS RT-AX88U Pro":           "https://dlcdnwebimgs.asus.com/gain/RT-AX88U-PRO/W1T/1M.jpg",
  "ASUS RT-AX58U":               "https://dlcdnwebimgs.asus.com/gain/RT-AX58U/W1T/1M.jpg",
  "Netgear Nighthawk RAXE500":   "https://www.netgear.com/images/Products/Networking/Routers/WiFi6E/RAXE500/RAXE500_main.png",
  "Netgear Nighthawk AX12":      "https://www.netgear.com/images/Products/Networking/Routers/WiFi6/RAX120/RAX120_main.png",
  "TP-Link Archer AX90":         "https://static.tp-link.com/2020/202009/20200925/Archer%20AX90_un_v1.0.png",
  "TP-Link Archer AX73":         "https://static.tp-link.com/2021/202110/20211012/Archer%20AX73_un_v1.0.png",
  "TP-Link Archer AX55":         "https://static.tp-link.com/2021/202104/20210412/Archer%20AX55_un_v1.0.png",
  "Linksys Velop MX12600":       "https://www.linksys.com/on/demandware.static/-/Sites-masterCatalog/default/dw6c1b5f24/images/highres/MX12600_Front_Angle.jpg",
  "Linksys Hydra Pro 6":         "https://www.linksys.com/on/demandware.static/-/Sites-masterCatalog/default/dw3c1b5f24/images/highres/E8450_Front_Angle.jpg",
  "Ubiquiti UniFi 6 Enterprise": "https://cdn.shopify.com/s/files/1/0883/0710/products/U6-Enterprise-Back_1024x1024.jpg",
  "Ubiquiti UniFi 6 Lite":       "https://cdn.shopify.com/s/files/1/0883/0710/products/U6-Lite-Back_1024x1024.jpg",
  "ASUS PCE-AXE59BTX":           "https://dlcdnwebimgs.asus.com/gain/PCE-AXE59BTX/W1T/1M.jpg",
  "TP-Link Archer TX50X":        "https://static.tp-link.com/2022/202201/20220111/Archer%20TX50X_un_v1.0.png",
  "Devolo Magic 2 WiFi 6":       "https://www.devolo.global/fileadmin/Media/Images/Product/magic-2-wifi6/magic2-wifi6-adapter-front.png",

  // ═══ FOTOGRAFIE ═══
  "Sony Alpha A7 IV":      "https://www.sony.nl/image/5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Sony Alpha A7C II":     "https://www.sony.nl/image/6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Sony Alpha A7R V":      "https://www.sony.nl/image/7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d?fmt=pjpeg&bgcolor=FFFFFF&bgc=FFFFFF&wid=1200&hei=1200",
  "Canon EOS R6 Mark II":  "https://www.canon.nl/media/EOS_R6_Mark_II_Front_tcm88-2355521.png",
  "Canon EOS R8":          "https://www.canon.nl/media/EOS_R8_Front_tcm88-2246614.png",
  "Canon EOS R50":         "https://www.canon.nl/media/EOS_R50_Front_tcm88-2185386.png",
  "Nikon Z8":              "https://www.nikon.nl/nl_NL/content/nikon/products/cameras/nikon-z-8/nikon-z8-front.png",
  "Nikon Z6 III":          "https://www.nikon.nl/nl_NL/content/nikon/products/cameras/nikon-z-6III/nikon-z6III-front.png",
  "Nikon Z50 II":          "https://www.nikon.nl/nl_NL/content/nikon/products/cameras/nikon-z-50II/nikon-z50II-front.png",
  "Fujifilm X-T5":         "https://fujifilm-x.com/wp-content/uploads/2022/11/X-T5_Silver_Front-Top.png",
  "Fujifilm X100VI":       "https://fujifilm-x.com/wp-content/uploads/2024/02/X100VI_Silver_Front.png",
  "Panasonic Lumix GH6":   "https://panasonic.net/cns/sav/products/lumix/gh6/img/kv_main.png",
  "Panasonic Lumix S5 II": "https://panasonic.net/cns/sav/products/lumix/s5m2/img/kv_main.png",
  "OM System OM-1 Mark II":"https://om-digitalsolutions.co.jp/cms/wp-content/uploads/2023/12/OM-1MarkII_front.png",
  "Hasselblad X2D 100C":   "https://www.hasselblad.com/globalassets/x2d/hasselblad-x2d-100c-product-shot.png",

  // ═══ HUISHOUDELIJK ═══
  "Dyson V15 Detect":           "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/vacuum-cleaners/sticks/v15-detect/nickel-yellow/348040-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson V12 Detect Slim":      "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/vacuum-cleaners/sticks/dyson-v12-detect-slim-absolute/nickel-yellow/352241-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson Gen5detect":           "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/vacuum-cleaners/sticks/gen5detect/nickel-yellow/390025-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson Airwrap Complete":     "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-airwrap/nickel-copper-limited-edition/452606-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson Supersonic":           "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/hair-care/dyson-supersonic/fuschia-bright-nickel/453956-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson Big Ball Multifloor 2":"https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/vacuum-cleaners/cylinders/big-ball-multi-floor-2/iron-nickel/2L77009.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "Dyson 360 Vis Nav":          "https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/products/robot-vacuum-cleaners/360-vis-nav/nickel-yellow/446650-01.png?$responsive$&cropPathE=desktop&fit=stretch,1&wid=960",
  "iRobot Roomba j7+":          "https://store.irobot.com/default/dw/image/v2/AGHH_PRD/on/demandware.static/-/Sites-master-catalog-irobot/default/dwd6a6b0c7/images/large/j7-plus-roomba-main.png?sw=550&sh=550&sm=fit",
  "iRobot Roomba s9+":          "https://store.irobot.com/default/dw/image/v2/AGHH_PRD/on/demandware.static/-/Sites-master-catalog-irobot/default/dw2a0f3b4a/images/large/s9-plus-roomba-main.png?sw=550&sh=550&sm=fit",
  "Roborock S8 Pro Ultra":      "https://static.roborock.com/images/product/s8-pro-ultra/main.png",
  "Roborock Q Revo":            "https://static.roborock.com/images/product/q-revo/main.png",
  "Ecovacs Deebot X2 Omni":     "https://ecovacs.com/cdn/shop/products/DEEBOT-X2-OMNI-Product-Page-1.png",
  "Philips Airfryer XXL Premium":"https://images.philips.com/is/image/philipsconsumer/hd9867_90-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Philips SensoTouch 9000 Series":"https://images.philips.com/is/image/philipsconsumer/sp9893_17-nl-nl?wid=800&hei=800&fmt=jpeg",
  "Braun Silk-epil 9 Flex":     "https://www.braun.com/content/dam/braun/global/women/epilation/silk-epil-9/silk-epil-9-flex/91-flex/gallery/silk-epil-9-flex-gallery-1.jpg",

  // ═══ WEARABLES ═══
  "Apple Watch Ultra 2":         "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-ultra-2-orange-alpine-loop-202309?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple Watch Series 10 46mm":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-s10-46-jet-black-sb-case-jet-black-sport-band-202409?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple Watch Series 10 42mm":  "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-s10-42-jet-black-sb-case-jet-black-sport-band-202409?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Apple Watch SE 40mm":         "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/watch-se-starlight-case-starlight-sport-band-202309?wid=800&hei=800&fmt=jpeg&qlt=90",
  "Samsung Galaxy Watch Ultra":  "https://images.samsung.com/nl/galaxy-watch/products/galaxy-watch-ultra/images/galaxy-watch-ultra-titaniumwhite-front.jpg",
  "Samsung Galaxy Watch 7 44mm": "https://images.samsung.com/nl/galaxy-watch/products/galaxy-watch7/images/galaxy-watch7-44mm-green-front.jpg",
  "Samsung Galaxy Watch 7 40mm": "https://images.samsung.com/nl/galaxy-watch/products/galaxy-watch7/images/galaxy-watch7-40mm-green-front.jpg",
  "Samsung Galaxy Watch FE":     "https://images.samsung.com/nl/galaxy-watch/products/galaxy-watch-fe/images/galaxy-watch-fe-graphite-front.jpg",
  "Google Pixel Watch 3 45mm":   "https://lh3.googleusercontent.com/nu9PpVf0_9D-s3JEHSNn2hH7_rnv3FH3IxV4EBUiGJnnqHsBEPuPOQHZRJBfDfCNqeXlEeVT",
  "Google Pixel Watch 3 41mm":   "https://lh3.googleusercontent.com/mu8OooUe8_8C-r2DGFMm1gG6qqm2EGG2JyU3DATjHImmprGADFoQPPGISIAEEoCMpDYkmDDU",
  "Garmin Fenix 7X Pro":         "https://res.garmin.com/transform/image/upload/b_rgb:FFFFFF,c_lpad,dpr_2.0,f_auto,h_568,q_auto,w_568/c_lpad,h_568,w_568/v1/Product_Images/en/products/010-02778-01/v/cf-xl@2x",
  "Garmin Forerunner 965":       "https://res.garmin.com/transform/image/upload/b_rgb:FFFFFF,c_lpad,dpr_2.0,f_auto,h_568,q_auto,w_568/c_lpad,h_568,w_568/v1/Product_Images/en/products/010-02809-01/v/cf-xl@2x",
  "Garmin Venu 3":               "https://res.garmin.com/transform/image/upload/b_rgb:FFFFFF,c_lpad,dpr_2.0,f_auto,h_568,q_auto,w_568/c_lpad,h_568,w_568/v1/Product_Images/en/products/010-02784-00/v/cf-xl@2x",
  "Fitbit Sense 2":              "https://www.fitbit.com/global/content/assets/devices/sense2/shadow-grey/sense2-shadow-grey-front.png",
  "Fitbit Charge 6":             "https://www.fitbit.com/global/content/assets/devices/charge6/obsidian/charge6-obsidian-front.png",
};

const filePath = path.join(__dirname, '../data/products.json');
const products = JSON.parse(fs.readFileSync(filePath, 'utf8'));

let updated = 0;
const result = products.map(p => {
  if (imageMap[p.name]) {
    updated++;
    return { ...p, imageUrl: imageMap[p.name] };
  }
  return p;
});

const notFound = products.filter(p => !imageMap[p.name]).map(p => p.name);
console.log(`Updated: ${updated} / ${products.length}`);
if (notFound.length) console.log('Not mapped:', notFound.join(', '));

fs.writeFileSync(filePath, JSON.stringify(result, null, 2));
console.log('products.json saved.');
